In [41]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.12.0


In [42]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

In [43]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_1 (Flatten)         (None, 784)               0         
                                                                 
 dense_2 (Dense)             (None, 128)               100480    
                                                                 
 dropout_1 (Dropout)         (None, 128)               0         
                                                                 
 dense_3 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101,770
Trainable params: 101,770
Non-trainable params: 0
_________________________________________________________________


In [44]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.28819665,  0.9838307 ,  0.10433807, -0.2666812 ,  0.28392285,
        -0.04540448, -0.05787534, -0.19223484, -0.4169047 ,  0.05425736]],
      dtype=float32)

In [45]:
tf.nn.softmax(predictions).numpy()

array([[0.06772897, 0.24166231, 0.10028826, 0.06920198, 0.12001701,
        0.08634114, 0.08527107, 0.07455043, 0.05954938, 0.09538946]],
      dtype=float32)

In [46]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()

2.449449

In [47]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.2921 - accuracy: 0.9157
Epoch 2/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1408 - accuracy: 0.9579
Epoch 3/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1072 - accuracy: 0.9667
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0858 - accuracy: 0.9740
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0758 - accuracy: 0.9761


In [48]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0724 - accuracy: 0.9773 - 580ms/epoch - 2ms/step


[0.0723869726061821, 0.9772999882698059]

In [49]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [50]:
y_test[:5]

array([7, 2, 1, 0, 4], dtype=uint8)

In [51]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.30414979e-07, 1.02883113e-09, 4.87378338e-06, 3.08456183e-05,
        2.41129061e-11, 3.39841961e-07, 1.05483775e-12, 9.99953032e-01,
        1.70456033e-07, 1.02431695e-05],
       [5.49930212e-10, 5.47226919e-05, 9.99944925e-01, 3.05311346e-07,
        1.40421612e-16, 9.75146630e-09, 6.36448783e-10, 2.12744197e-13,
        1.91803518e-10, 4.93538189e-15],
       [1.12790673e-07, 9.97453153e-01, 1.41443903e-04, 2.95481332e-05,
        2.93309677e-05, 1.08547109e-04, 7.33395837e-06, 2.05871114e-03,
        1.71273670e-04, 4.90210027e-07],
       [9.99872565e-01, 5.99008398e-09, 3.75559830e-05, 6.26377073e-07,
        1.58119377e-07, 7.34053128e-06, 1.17415748e-05, 7.02640909e-06,
        1.10252756e-07, 6.27882400e-05],
       [5.96105210e-08, 4.69156354e-12, 2.19838100e-07, 4.14929036e-10,
        9.99412060e-01, 1.41056049e-07, 3.18862226e-06, 2.33409878e-06,
        3.01055621e-07, 5.81517874e-04]], dtype=float32)>

In [52]:
import numpy as np
np.argmax(probability_model(x_test[2:3]))

1

In [53]:
# Grab an image from the test dataset.
img = x_test[4]
print(img.shape)

(28, 28)


In [54]:
# Add the image to a batch where it's the only member.
img = (np.expand_dims(img,0))
print(img.shape)

(1, 28, 28)


In [55]:
predictions_single = probability_model.predict(img)
print(predictions_single)
print(np.argmax(predictions_single))

1/1 [==============================] - 0s 59ms/step
[[5.9610294e-08 4.6915453e-12 2.1983747e-07 4.1492590e-10 9.9941206e-01
  1.4105565e-07 3.1886102e-06 2.3340876e-06 3.0105446e-07 5.8151566e-04]]
4
